<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>70092a41-b32e-4db9-b9b1-f0db8cf9d06b</UserSecretsId>
		<RootNamespace>La_Esperanza</RootNamespace>
		<CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
		<StartupObject>La_Esperanza.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Apple\**" />
		<Content Remove="Apple\**" />
		<EmbeddedResource Remove="Apple\**" />
		<None Remove="Apple\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="bundleconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="La Esperanza.csproj.vspscc" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
		<PackageReference Include="Rotativa.NetCore" Version="1.0.4" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.6" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
		<PackageReference Include="WebEssentials.AspNetCore.PWA" Version="1.0.85" />
		<PackageReference Include="WebPush-NetCore" Version="1.0.2" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\lib\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="bundleconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Rotativa\wkhtmltoimage.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Rotativa\wkhtmltopdf.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Rotativa\wkhtmltox.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>