//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaEsperanza.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaEsperanza.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The API is up and running.
        /// </summary>
        internal static string API_WELCOME {
            get {
                return ResourceManager.GetString("API_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have incorrectly attempted {0} of {1} times, until your account will be blocked..
        /// </summary>
        internal static string ERROR_ACCOUNT_ATTEMPT_COUNTER {
            get {
                return ResourceManager.GetString("ERROR_ACCOUNT_ATTEMPT_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is incorrect..
        /// </summary>
        internal static string ERROR_ACCOUNT_PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_ACCOUNT_PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account is blocked, contact your administrator..
        /// </summary>
        internal static string ERROR_ACCOUNT_USER_LOCKED {
            get {
                return ResourceManager.GetString("ERROR_ACCOUNT_USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not exists..
        /// </summary>
        internal static string ERROR_ACCOUNT_USER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_ACCOUNT_USER_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The customer wasn&apos;t added. Try again..
        /// </summary>
        internal static string ERROR_CUSTOMER_ADD {
            get {
                return ResourceManager.GetString("ERROR_CUSTOMER_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t get the customer information..
        /// </summary>
        internal static string ERROR_CUSTOMER_GET {
            get {
                return ResourceManager.GetString("ERROR_CUSTOMER_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The customer wasn&apos;t updated. Try again..
        /// </summary>
        internal static string ERROR_CUSTOMER_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_CUSTOMER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uops! Something went wrong..
        /// </summary>
        internal static string ERROR_EXCEPTION_TITLE {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t add the ordeer. Try again..
        /// </summary>
        internal static string ERROR_ORDER_ADD {
            get {
                return ResourceManager.GetString("ERROR_ORDER_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t cancel the order. Try again..
        /// </summary>
        internal static string ERROR_ORDER_CANCEL {
            get {
                return ResourceManager.GetString("ERROR_ORDER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t get the order information..
        /// </summary>
        internal static string ERROR_ORDER_GET {
            get {
                return ResourceManager.GetString("ERROR_ORDER_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t move the order to the next process..
        /// </summary>
        internal static string ERROR_ORDER_MOVED {
            get {
                return ResourceManager.GetString("ERROR_ORDER_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t reject the order. Try again..
        /// </summary>
        internal static string ERROR_ORDER_REJECT {
            get {
                return ResourceManager.GetString("ERROR_ORDER_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t perform the search requested..
        /// </summary>
        internal static string ERROR_ORDER_SEARCH {
            get {
                return ResourceManager.GetString("ERROR_ORDER_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t modify the order. Try again..
        /// </summary>
        internal static string ERROR_ORDER_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_ORDER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product wasn&apos;t added. Try again..
        /// </summary>
        internal static string ERROR_PRODUCT_ADD {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t get the product information..
        /// </summary>
        internal static string ERROR_PRODUCT_GET {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product wasn&apos;t updated. Try again..
        /// </summary>
        internal static string ERROR_PRODUCT_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_PRODUCT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is required..
        /// </summary>
        internal static string ERROR_VALIDATION_LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_VALIDATION_LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is required..
        /// </summary>
        internal static string ERROR_VALIDATION_LOGIN_USERNAME {
            get {
                return ResourceManager.GetString("ERROR_VALIDATION_LOGIN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has canceled the order with number {1} because {2}.
        /// </summary>
        internal static string PUSH_ORDER_MESSAGE_CANCEL {
            get {
                return ResourceManager.GetString("PUSH_ORDER_MESSAGE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has delivered the order with number {1} and charged {2}..
        /// </summary>
        internal static string PUSH_ORDER_MESSAGE_DELIVER {
            get {
                return ResourceManager.GetString("PUSH_ORDER_MESSAGE_DELIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has moved the order number {1} to process {2}..
        /// </summary>
        internal static string PUSH_ORDER_MESSAGE_MOVED {
            get {
                return ResourceManager.GetString("PUSH_ORDER_MESSAGE_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has created a new order with number {1}..
        /// </summary>
        internal static string PUSH_ORDER_MESSAGE_NEW {
            get {
                return ResourceManager.GetString("PUSH_ORDER_MESSAGE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has rejected the order with number {1} because {2}.
        /// </summary>
        internal static string PUSH_ORDER_MESSAGE_REJECT {
            get {
                return ResourceManager.GetString("PUSH_ORDER_MESSAGE_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has modified the order with number {1}..
        /// </summary>
        internal static string PUSH_ORDER_MESSAGE_UPDATE {
            get {
                return ResourceManager.GetString("PUSH_ORDER_MESSAGE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order canceled!.
        /// </summary>
        internal static string PUSH_ORDER_TITLE_CANCEL {
            get {
                return ResourceManager.GetString("PUSH_ORDER_TITLE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order delivered!.
        /// </summary>
        internal static string PUSH_ORDER_TITLE_DELIVER {
            get {
                return ResourceManager.GetString("PUSH_ORDER_TITLE_DELIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order moved!.
        /// </summary>
        internal static string PUSH_ORDER_TITLE_MOVED {
            get {
                return ResourceManager.GetString("PUSH_ORDER_TITLE_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New order!.
        /// </summary>
        internal static string PUSH_ORDER_TITLE_NEW {
            get {
                return ResourceManager.GetString("PUSH_ORDER_TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order rejected!.
        /// </summary>
        internal static string PUSH_ORDER_TITLE_REJECT {
            get {
                return ResourceManager.GetString("PUSH_ORDER_TITLE_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order updated!.
        /// </summary>
        internal static string PUSH_ORDER_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PUSH_ORDER_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ----- Select -----.
        /// </summary>
        internal static string SELECT_ITEM_EMPTY {
            get {
                return ResourceManager.GetString("SELECT_ITEM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Ready to deliver&quot;.
        /// </summary>
        internal static string STATUS_NAME_DELIVER {
            get {
                return ResourceManager.GetString("STATUS_NAME_DELIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Processing&quot;.
        /// </summary>
        internal static string STATUS_NAME_PROCESSING {
            get {
                return ResourceManager.GetString("STATUS_NAME_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The customer was added successfully..
        /// </summary>
        internal static string SUCCESS_CUSTOMER_ADD {
            get {
                return ResourceManager.GetString("SUCCESS_CUSTOMER_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The customer was updated successfully..
        /// </summary>
        internal static string SUCCESS_CUSTOMER_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_CUSTOMER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order with number {0} was added successfully..
        /// </summary>
        internal static string SUCCESS_ORDER_ADD {
            get {
                return ResourceManager.GetString("SUCCESS_ORDER_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order with number {0} was canceled successfully..
        /// </summary>
        internal static string SUCCESS_ORDER_CANCEL {
            get {
                return ResourceManager.GetString("SUCCESS_ORDER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order with number {0} was moved to next process successfully..
        /// </summary>
        internal static string SUCCESS_ORDER_MOVED {
            get {
                return ResourceManager.GetString("SUCCESS_ORDER_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order with number {0} was rejected successfully..
        /// </summary>
        internal static string SUCCESS_ORDER_REJECT {
            get {
                return ResourceManager.GetString("SUCCESS_ORDER_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The order with number {0} was updated successfully..
        /// </summary>
        internal static string SUCCESS_ORDER_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_ORDER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product was added successfully..
        /// </summary>
        internal static string SUCCESS_PRODUCT_ADD {
            get {
                return ResourceManager.GetString("SUCCESS_PRODUCT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The product was updated successfully..
        /// </summary>
        internal static string SUCCESS_PRODUCT_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_PRODUCT_UPDATE", resourceCulture);
            }
        }
    }
}
